Create the mobile website section to list the portfolio projects
d4nQw3rty/project_portfolio pull request #6
Opened 2022-07-06 15:01 UTC by d4nQw3rty

*Create the main container using CSS Grid to contain all the cards
*Use Flexbox to lay out an individual card.
*Implement the button interactions (enable, hover, etc).
*Build About myself section.

2022-07-07 18:04 UTC, vechicin requested changes
# Hi @d4nQw3rty ✋, 

Good job so far! 🔥 
There are some issues that you still need to work on to go to the next project but you are almost there! 🚨 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 📂 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-07 18:04 UTC, vechicin commented on index.html
> +                       <button type="button" class="button-enable button-enable-text" >See Project</button>
Your buttons don't have the required interaction stylings. Please add them to all.

<img width="832" alt="Screen Shot 2022-07-07 at 12 06 07" src="https://user-images.githubusercontent.com/82426682/177830497-25da6de8-92e0-4cb9-9e3d-ae982020fd4f.png">

2022-07-07 18:04 UTC, vechicin commented on index.html
> +         <section id="main-container">
This section doesn't have the margins defined in the Figma template. Please fix them.

<img width="227" alt="Screen Shot 2022-07-07 at 12 07 13" src="https://user-images.githubusercontent.com/82426682/177830662-6c5a0a72-f7b8-4fe7-a213-1ed3311e848d.png">

<img width="488" alt="Screen Shot 2022-07-07 at 12 07 31" src="https://user-images.githubusercontent.com/82426682/177830705-4211468a-8cc1-4d24-8fb5-44a84cc59484.png">

2022-07-07 18:04 UTC, vechicin commented on index.html
> +                    <p class="Lets-Connect">LET’S CONNECT</p>
This content should be wrapped in an `<hx>`.

<img width="439" alt="Screen Shot 2022-07-07 at 12 23 15" src="https://user-images.githubusercontent.com/82426682/177833308-36fa2240-88d6-40e0-870c-1811219b4de1.png">

2022-07-07 18:04 UTC, vechicin commented on index.html
> +                 </ul>
The order of the icons doesn't match that of the template design. Please take a look at the Figma template and fix it.

2022-07-07 18:04 UTC, vechicin commented on index.html
> +                      <button type="button" class="button-enable button-enable-text">Get my resume</button>
Your button doesn't have interaction styling. Please take a look at the previous comment and fix it.

2022-07-07 18:04 UTC, vechicin commented on style.css
> +  font-weight: 700;
None of your `font-weight` rules are working. That is most likely caused by not importing the correct font weight from Google Fonts. Please refer to [this video](https://www.youtube.com/watch?v=mRoBBOTYNz4&t=184s) to fix this issue.

<img width="560" alt="Screen Shot 2022-07-07 at 13 03 24" src="https://user-images.githubusercontent.com/82426682/177839886-46fd92fa-3d02-45e2-8859-e546b760a981.png">

2022-07-08 20:59 UTC, vickymarz approved these changes
Hi @d4nQw3rty , 

# 🟢  Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-08 21:07 UTC, merged